# Generated by Django 4.1.11 on 2024-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinformation',
            name='dateAndTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
