# Generated by Django 4.1.11 on 2024-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0002_alter_dailyinformation_dateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinformation',
            name='userName',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
