# Generated by Django 4.1.11 on 2024-07-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0003_dailyinformation_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthsummery',
            name='userName',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeksummery',
            name='userName',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
